CREATE TABLE IF NOT EXISTS communities (
    id UUID PRIMARY KEY NOT NULL DEFAULT GEN_RANDOM_UUID(),
    name VARCHAR(100) NOT NULL,
    description TEXT,
    location VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at BIGINT default 0
);